### PR TITLE
change of user inside container possible

### PR DESCRIPTION
**Pull request by ghost**
Switching to alpine-mono may solve issue #8.
Needs testing.

### CODE REVIEW

**Comment by petemounce** [comment]
Thanks for effort! I tried it out - I built the image via 

```shell
pete at pete-mac402 in ~/src/github/mono-choco (remotes/kobilous/master●)
$ docker build -t choco-kobilous .
```

and then attempted my `push`, got the same error:

```
Attempting to push bazel.0.11.0-rc2.nupkg to https://push.chocolatey.org/
Got a bad hardware address length for an AF_PACKET 16 8
Got a bad hardware address length for an AF_PACKET 16 8
Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /home/buildozer/aports/testing/mono/src/mono-5.2.0.224/external/boringssl/ssl/handshake_client.c:1132)
```

**Comment by Linuturk** [comment]
Thanks for the PR but I do prefer to install mono myself inside alpine using the official alpine testing package vs compiling it myself.

I do like some of your changes, specifically:

- additional checks on the cleanup trap
- assuming a user
- defaulting to the help output when a command isn't specified

I'll take a look at those pieces and possibly incorporate them.

**Comment by Linuturk** [comment]
I pulled everything except the dependency on frolvlad/alpine-mono and the user changing work. It's a much cleaner setup for someone to just COPY their package into the container and run the pack and publish from inside the container, and I want to encourage that workflow versus the volume mount.

**Comment by ghost** [comment]
Do I assume correctly that you (@Linuturk) are not entirely against my user changing work?
Just the current state of it doesn't meet your standards, right?
If so, I would wait for @petemounce to confirm the fix for #8 and than incorporate the switch to debian before updating PR.

**Comment by petemounce** [comment]
I just pulled 40c9796 from @kobilous and rebuilt the container locally, then re-ran my package build process; same SSL issue.

```shell
Attempting to push bazel.0.11.0-rc2.nupkg to https://push.chocolatey.org/
Got a bad hardware address length for an AF_PACKET 16 8
Got a bad hardware address length for an AF_PACKET 16 8
Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /home/buildozer/aports/testing/mono/src/mono-5.2.0.224/external/boringssl/ssl/handshake_client.c:1132)
```

**Comment by ghost** [comment]
Sorry @petemounce for misguiding you.
I meant Linuturk/mono-choco@eb29d35b44dd877f47781ab9800e135ac9d4e1a6.

**Comment by petemounce** [comment]
Still TrustFailure :( 

I've updated bazelbuild/bazel#4559 to illustrate how I'm trying now via a docker build instead of docker run - this has made no difference to the outcome.

Against eb29d35 I got:

```
Attempting to push bazel.0.11.0-rc2.nupkg to https://push.chocolatey.org/
Chocolatey had an error occur:
System.Net.WebException: Error: TrustFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x00040] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult result) [0x0003b] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult asyncResult) [0x0000c] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.EndRead (System.IAsyncResult asyncResult) [0x00057] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
  at Mono.Net.Security.Private.LegacySslStream.EndAuthenticateAsClient (System.IAsyncResult asyncResult) [0x00011] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at Mono.Net.Security.Private.LegacySslStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x0000e] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at Mono.Net.Security.MonoTlsStream.CreateStream (System.Byte[] buffer) [0x00044] in <bd46d4d4f7964dfa9beea098499ab597>:0
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00064] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at NuGet.RequestHelper.GetResponse () [0x0011c] in <3b8b1d8d279c4abe86d7354e54b7831f>:0
Exiting with 1
The command '/bin/sh -c choco push --verbose --debug --timeout 30 /tmp/${PACKAGE}.${VERSION}.nupkg --apikey "${API_KEY}"' returned a non-zero code: 1
```

Against `linuturk/mono-choco:latest` as of now I got:

```
_ Chocolatey:ChocolateyPushCommand - Normal Run Mode _
Attempting to push bazel.0.11.0-rc2.nupkg to https://push.chocolatey.org/
Chocolatey had an error occur:
System.Net.WebException: Error: TrustFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x00040] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult result) [0x0003b] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult asyncResult) [0x0000c] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.EndRead (System.IAsyncResult asyncResult) [0x00057] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
  at Mono.Net.Security.Private.LegacySslStream.EndAuthenticateAsClient (System.IAsyncResult asyncResult) [0x00011] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at Mono.Net.Security.Private.LegacySslStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x0000e] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at Mono.Net.Security.MonoTlsStream.CreateStream (System.Byte[] buffer) [0x00044] in <bd46d4d4f7964dfa9beea098499ab597>:0
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00064] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at NuGet.RequestHelper.GetResponse () [0x0011c] in <3b8b1d8d279c4abe86d7354e54b7831f>:0
Exiting with 1
The command '/bin/sh -c choco push --force --verbose --debug --timeout 30 /tmp/${PACKAGE}.${VERSION}.nupkg --apikey "${API_KEY}"' returned a non-zero code: 1
```

**Pull request closed without merging**
